version: 2
updates:
- package-ecosystem: pip
  directory: "/dvp"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot/add-v2-config-file
  ignore:
  - dependency-name: packaging
    versions:
    - "20.8"
- package-ecosystem: pip
  directory: "/common"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot/add-v2-config-file
  ignore:
  - dependency-name: packaging
    versions:
    - "20.8"
- package-ecosystem: pip
  directory: "/platform"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot/add-v2-config-file
  ignore:
  - dependency-name: packaging
    versions:
    - "20.8"
- package-ecosystem: pip
  directory: "/libs"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot/add-v2-config-file
  ignore:
  - dependency-name: packaging
    versions:
    - "20.8"
- package-ecosystem: pip
  directory: "/tools"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot/add-v2-config-file
  ignore:
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest-cov
    versions:
    - 2.10.1
