site_name: Delphix Virtualization SDK
theme: 
  name: material
  custom_dir: 'material/'
  palette:
    primary: 
    accent: 
  logo: 'images/delphix-logo-white.png'
  favicon: 'images/logo.png'
  font:
    text: Helvetica Neue
    code: Ubuntu Mono

copyright: Copyright &copy; 2019 Delphix Corp.

google_analytics:
  - 'UA-35429885-3'
  - 'auto'

extra:
  social:
    - type: sitemap
      link: https://www.delphix.com/
    - type: facebook
      link: https://www.facebook.com/DelphixCorp/
    - type: twitter
      link: https://twitter.com/delphix
    - type: linkedin
      link: https://www.linkedin.com/company/delphix
    - type: github
      link: https://github.com/delphix

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - meta

plugins:
  - search
  - awesome-pages
