site_name: Delphix Virtualization SDK 4.0.0
theme:
  name: material
  custom_dir: 'material/'
  palette:
    primary:
    accent:
  logo: 'images/header_logo.png'
  favicon: 'images/favicon_logo.png'
  font:
    text: Helvetica Neue
    code: Ubuntu Mono
  feature:

copyright: Copyright &copy; 2022 Delphix Corp.

google_analytics:
  - 'UA-35429885-3'
  - 'auto'

extra:
  social:
    - type: sitemap
      link: https://www.delphix.com/
    - type: facebook
      link: https://www.facebook.com/DelphixCorp/
    - type: twitter
      link: https://twitter.com/delphix
    - type: linkedin
      link: https://www.linkedin.com/company/delphix
    - type: github
      link: https://github.com/delphix

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - meta

plugins:
  - search
  - awesome-pages
